/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_Restaurante;

import BancoDados.BancoClient;
import BancoDados.BancoRestaurant;
//import java.sql.Connection;
//import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
//import java.sql.SQLException;
import Classes.InfoC;

/**
 *
 * @author uniejoalbuquerque
 */
public class Restaurante extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    BancoRestaurant resta = new BancoRestaurant();
    BancoClient banco = new BancoClient();
    //private Connection conn;
    //private PreparedStatement pstm;
    //private ResultSet rs;
    String lista = "CPF       Pedido       Status";
    String checklista = lista;
    public Restaurante() {
        initComponents();
        
        try {
            ResultSet rs = resta.Lista();
            System.out.println("cheguei");
            while (rs.next()) {
                System.out.println("passei");
                lista = lista + ("\n"+rs.getString("CPF") + "     " + 
                        rs.getString("Produto")+"        "+rs.getString("Status"));
                
            }
            if(lista.equals(checklista)){
                lista = "Não há nada na fila";
                jTextArea.setText(lista);
            }
            else{
                String txt = resta.listadepedidos();
                jTextArea.setText(txt);
            }
        } 
        
        catch( Exception e) {
            lista = "Erro na conexão com o Banco de Dados";
            jTextArea.setText(lista);
        } 
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        setCPF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        setPronto = new javax.swing.JButton();
        setPreparando = new javax.swing.JButton();
        selectExcluir = new javax.swing.JButton();
        selectExtrato = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        selectExtrato1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(204, 0, 204));
        jDesktopPane1.setForeground(new java.awt.Color(255, 51, 204));
        jDesktopPane1.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pedidos na fila:");

        jLabel2.setText("Alterar Status:");

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cachorro Quente", "Misto Quente", "Refrigerante", "Salada de Frutas", "Suco Natural", "X-Burguer", "X-Salada" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        setCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCPFActionPerformed(evt);
            }
        });

        jLabel3.setText("Prato:");

        setPronto.setText("Pronto");
        setPronto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setProntoActionPerformed(evt);
            }
        });

        setPreparando.setText("Preparando");
        setPreparando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPreparandoActionPerformed(evt);
            }
        });

        selectExcluir.setText("Excluir Cliente");
        selectExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectExcluirActionPerformed(evt);
            }
        });

        selectExtrato.setText("Extrato dos clientes");
        selectExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectExtratoActionPerformed(evt);
            }
        });

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane2.setViewportView(jTextArea);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ratatao.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Britannic Bold", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Software para uso da cozinha");

        jLabel7.setText("CPF:");

        jLabel8.setFont(new java.awt.Font("Bernard MT Condensed", 2, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LOS BROTHERS");

        selectExtrato1.setText("Contas Cadastradas");
        selectExtrato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectExtrato1ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(setCPF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(setPronto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(setPreparando, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(selectExcluir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(selectExtrato, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(selectExtrato1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(setCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(16, 16, 16))
                                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(setPreparando)
                                                        .addComponent(setPronto))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(selectExtrato1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(selectExtrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(selectExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)))
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 33, Short.MAX_VALUE))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(setCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(setPreparando)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setPronto)
                        .addGap(27, 27, 27)
                        .addComponent(selectExcluir)
                        .addGap(8, 8, 8)
                        .addComponent(selectExtrato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectExtrato1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectExtratoActionPerformed
        // TODO add your handling code here:
        Restaurante.this.dispose();
        new BuscaPedido().setVisible(true);
    }//GEN-LAST:event_selectExtratoActionPerformed

    private void selectExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectExcluirActionPerformed
        // TODO add your handling code here:
        String cpf = JOptionPane.showInputDialog (null, "Informe o CPF à ser deletado", "Excluir cliente",
    JOptionPane.QUESTION_MESSAGE);
//        int cpf = Integer.parseInt(scpf);
        System.out.println(cpf);
        
        try{
            resta.remover(cpf);
            resta.removerFila(cpf);
            banco.remover(cpf);
            String txt = resta.listadepedidos();
            jTextArea.setText(txt);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog (null, "Não foi possível remover", "ERRO",
    JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_selectExcluirActionPerformed

    private void setPreparandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPreparandoActionPerformed
        // TODO add your handling code here:
        String cpf = setCPF.getText();
        setCPF.setText("");
        String pedido = jComboBox.getSelectedItem()+"";
        try{
            boolean b = resta.AlterarStatus("Preparando...", cpf, pedido);
            if (!b)
                JOptionPane.showMessageDialog (null, "Pedido não encontrado", "ERRO",
    JOptionPane.WARNING_MESSAGE);
        }
        
        catch (Exception e){
            JOptionPane.showMessageDialog (null, "Falha de comunicação com o servidor", "ERRO",
    JOptionPane.WARNING_MESSAGE);
        }
        
        String txt = resta.listadepedidos();
        jTextArea.setText(txt);
        
    }//GEN-LAST:event_setPreparandoActionPerformed

    private void setProntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setProntoActionPerformed
        // TODO add your handling code here:
        String cpf = setCPF.getText();
        setCPF.setText("");
        String pedido = jComboBox.getSelectedItem()+"";
        try{
            String b = resta.removerProdRestaurante(cpf, pedido);
            resta.AlterarStatusHistPronto(cpf, pedido);
            JOptionPane.showMessageDialog (null, b, "STATYS",
    JOptionPane.INFORMATION_MESSAGE);
        }
        
        catch (Exception e){
            JOptionPane.showMessageDialog (null, "Falha de comunicação com o servidor", "ERRO",
    JOptionPane.WARNING_MESSAGE);
        }
        String txt = resta.listadepedidos();
        jTextArea.setText(txt);
    }//GEN-LAST:event_setProntoActionPerformed

    private void setCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setCPFActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void selectExtrato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectExtrato1ActionPerformed
        Restaurante.this.dispose();
        new ContaClientes().setVisible(true);
    }//GEN-LAST:event_selectExtrato1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JButton selectExcluir;
    private javax.swing.JButton selectExtrato;
    private javax.swing.JButton selectExtrato1;
    private javax.swing.JTextField setCPF;
    private javax.swing.JButton setPreparando;
    private javax.swing.JButton setPronto;
    // End of variables declaration//GEN-END:variables
}
